### ISSUE TITLE
o plugin esta instavel 

### ISSUE THREAD

**Issue by markusharum** [cypher256/java-extension-pack#1]
alterou as configurações de thema do vscode e instalou plugin de forma indesejada.

**Comment by cypher256** [comment]
Set the theme settings in User settings.json to your preference or leave it empty as follows:
(Please leave the entries. If there is no entry, [it will be set](https://github.com/cypher256/java-extension-pack#auto-default-settings).)

Command Palette (F1 or Ctrl/Cmd + Shift + P) `>Preferences: Open User Settings (JSON)`
```json
"workbench.colorCustomizations": {},
"editor.rulers": [],
```

Also, [uninstall](https://code.visualstudio.com/docs/editor/extension-marketplace#_uninstall-an-extension) any unnecessary Extensions individually. 
Updating will not reinstall uninstalled Extensions.

**Comment by cypher256** [comment]
To disable transparency, uninstall the GlassIt-VSC extension or set the following in settings.json.
```json
"glassit.alpha": 255,
```

**Comment by cypher256** [comment]
Removed the GlassIt-VSC extension.
