### ISSUE TITLE
problems to uninstall and got brown boxes in style at end of properties

### ISSUE THREAD

**Issue by terihylton** [cypher256/java-extension-pack#2]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.1
Commit: f7e5374bbb46d89b3e3b4d138e7c45fbb0e60393
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: Gitpod

Extension version: 2023.1225.0

**Comment by cypher256** [comment]
'Java Extension Pack Auto Config' includes the following extension. 
Try uninstalling it.

Trailing Spaces
https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces
