### ISSUE TITLE
"terminal.integrated.defaultProfile.osx" is always automatically modified to "JavaSE-21 LTS"

### ISSUE THREAD

**Issue by shequeen** [cypher256/java-extension-pack#3]
I set "terminal.integrated.defaultProfile.osx" to "JavaSE-1.8 LTS" but it still automatically becomes "JavaSE-21 LTS" after restarting vscode  after a few seconds

setting.json:
`"terminal.integrated.defaultProfile.osx"`: `"JavaSE-21 LTS",` // **will be automatically modified!!!**
`"java.configuration.runtimes"`: [
        {
            "name": "JavaSE-1.8",
            "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home",
            `"default": true`  // **NOT WORK....**
        },
        {
            "name": "JavaSE-11",
            "path": "/Users/xx/Library/Application Support/Code/User/globalStorage/pleiades.java-extension-pack-jdk/java/11"
        },
        {
            "name": "JavaSE-13",
            "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home"
        },
        {
            "name": "JavaSE-15",
            "path": "/usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home"
        },
        {
            "name": "JavaSE-17",
            "path": "/Users/xx/Library/Application Support/Code/User/globalStorage/pleiades.java-extension-pack-jdk/java/17"
        },
        {
            "name": "JavaSE-21",
            "path": "/Users/xx/Library/Application Support/Code/User/globalStorage/pleiades.java-extension-pack-jdk/java/21"
        },
        {
            "name": "JavaSE-22",
            "path": "/Users/xx/Library/Application Support/Code/User/globalStorage/pleiades.java-extension-pack-jdk/java/latest"
        }
    ],

**Comment by cypher256** [comment]
The issue occurred when a profile name containing a dot was specified in the defaultProfile.
I will fix it and release an update soon.

**Comment by cypher256** [comment]
2024.828.0 is now available.
