### ISSUE TITLE
It is overriding my terminal settings

### ISSUE THREAD

**Issue by thslopes** [cypher256/java-extension-pack#4]
It is overriding my terminal settings without ask for

**Comment by cypher256** [comment]
This issue can be resolved in one of the following ways:

* Add `"javaAutoConfig.enabled": false,` to your settings.json
* Copy the `terminal.integrated.profiles` entry and create it under a different name.
e.g. Copy `JavaSE-21 LTS` to `JavaSE-21 MyCustom` and edit it

Note: Profiles named `JavaSE-{n}` and `JavaSE-{n} LTS` in 'terminal.integrated.profiles' are managed profiles, and they will always be overwritten by configurations from `java.configuration.runtimes`.
https://github.com/cypher256/java-extension-pack?tab=readme-ov-file#terminal-auto-configuration

**Comment by sw0ok** [comment]
This also overrides `ZDOTDIR` env variable, as I mistakenly installed this it stopped resolving my `.zshrc` correctly because of that.

**Comment by cypher256** [comment]
To address this, I have updated the extension to check if the ZDOTDIR environment variable is already set. 
If it is, the extension will no longer override it in the settings.json file. 
However, if JAVA_HOME is set in the zsh configuration specified by the ZDOTDIR environment variable, it will take precedence, and the JAVA_HOME setting in the built-in .zshrc of this extension will be disabled.
Please update to the latest version of the extension and let us know if this resolves the issue.

Built-in .zshrc
```bash
if [ -r ~/.zshrc ]; then
	JAVA_HOME_BACKUP=$JAVA_HOME
	source ~/.zshrc
	if [ -n "$JAVA_HOME_BACKUP" ]; then
		export JAVA_HOME=$JAVA_HOME_BACKUP
	fi
fi
export PATH="$JAVA_HOME/bin:$AUTO_CONFIG_PATH:$PATH"
```

**Comment by bigcat26** [comment]
the extension messed up everything.
